# Generated by Django 4.0.6 on 2024-11-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_alter_produto_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
    ]
